run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all"]
  gosimple:
    checks: ["all"]

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - misspell
    - ineffassign
    - unconvert
    - goconst
    - gocritic
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-dirs:
    - kpls
  max-issues-per-linter: 0
  max-same-issues: 0
